INSERT INTO USER (ID, ACCOUNT_ID, PASSWORD, NICK_NAME, EMAIL, INTRODUCTION) VALUES (1, 'kyungrae', '1234', 'dingo', 'rlarudfo93@gmail.com', '예비 개발자');
INSERT INTO USER (ID, ACCOUNT_ID, PASSWORD, NICK_NAME, EMAIL, INTRODUCTION) VALUES (2, 'honux', '1234', 'honux', 'honux77@codesquad.kr', '개발의 신');

INSERT INTO QUESTION (ID, TITLE, CONTENT, CREATED_AT, WRITER_ID) VALUES (1, 'AOP는 무엇인가?', 'AOP와 접근 제한의 관계는 무엇일까?', CURRENT_TIMESTAMP, 1);
INSERT INTO QUESTION (ID, TITLE, CONTENT, CREATED_AT, WRITER_ID) VALUES (2, 'JPA N+1 쿼리 문제란?', '카테시안 곱이란?', CURRENT_TIMESTAMP, 2);

INSERT INTO ANSWER(ID, CONTENT, CREATED_AT, QUESTION_ID, WRITER_ID) VALUES (1, '오 궁금하네요. 공부해볼게요!!', CURRENT_TIMESTAMP, 1, 1);
INSERT INTO ANSWER(ID, CONTENT, CREATED_AT, QUESTION_ID, WRITER_ID) VALUES (2, '그거는 말입니다!!', CURRENT_TIMESTAMP, 1, 2);
