INSERT INTO USER (USER_ID, NAME, PASSWORD, EMAIL) VALUES ('kses1010', 'Sunny', '123', 'kses1010@gmail.com');
INSERT INTO USER (USER_ID, NAME, PASSWORD, EMAIL) VALUES ('qwerty', 'Hello', 'abc', 'hihi@naver.com');

INSERT INTO QUESTION (ID, CONTENTS, FORMATTED_WRITTEN_TIME, TITLE, WRITER_ID) VALUES (1, '테스트입니다.1', CURRENT_TIMESTAMP, '테스트1', 1);
INSERT INTO QUESTION (ID, CONTENTS, FORMATTED_WRITTEN_TIME, TITLE, WRITER_ID) VALUES (2, '테스트입니다.2', CURRENT_TIMESTAMP, '테스트2', 2);
