INSERT INTO USER (USER_ID, PASSWORD, NAME , EMAIL) VALUES ('ever', 'asd', '이름1', 'hsik0225@gmail.com');
INSERT INTO USER (USER_ID, PASSWORD, NAME , EMAIL) VALUES ('ever2', 'qwe', '이름2', 'hrifle@gmail.com');

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATED_AT, MODIFIED_AT, REPLY_COUNT) VALUES (NULL, 1, '자바', '재밌는 코딩', NOW(), NOW(), 1);

INSERT INTO ANSWER (ID, WRITER_ID, QUESTION_ID, CONTENTS, CREATED_AT, MODIFIED_AT) VALUES (NULL, 2, 1, '열심히 해보죠', NOW(), NOW());
